name: Wheels

on: [push, pull_request, workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  macos:
    uses: ./.github/workflows/wheels-macos.yml
    with:
      build-commit: "HEAD"
      artifacts-name: "wheels"

  linux:
    uses: ./.github/workflows/wheels-linux.yml
    with:
      build-commit: "HEAD"
      artifacts-name: "wheels"

  macos-latest:
    if: "!startsWith(github.ref, 'refs/tags/')"
    uses: ./.github/workflows/wheels-macos.yml
    with:
      build-commit: "main"
      artifacts-name: "wheels-latest"

  combine:
    needs: [macos, linux, macos-latest, linux-latest]
    runs-on: ubuntu-latest
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: my-artifact
          pattern: wheels-*
          merge-multiple: true
      - name: Upload Combined Artifacts
        uses: actions/upload-artifact@v4
        with:
          path: my-artifact
          name: wheels-combined

  linux-latest:
    if: "!startsWith(github.ref, 'refs/tags/')"
    uses: ./.github/workflows/wheels-linux.yml
    with:
      build-commit: "main"
      artifacts-name: "wheels-latest"

  release:
    name: Create Release
    runs-on: ubuntu-latest
    if: "startsWith(github.ref, 'refs/tags/')"
    needs: [macos, linux]
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: wheels
      - name: Upload Release
        uses: fnkr/github-action-ghr@v1.3
        env:
          GHR_PATH: .
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  success:
    needs: [macos, linux, macos-latest, linux-latest]
    runs-on: ubuntu-latest
    name: Wheels Successful
    steps:
      - name: Success
        run: echo Wheels Successful
